### PR TITLE
JDK 17 on CI (Docker image)

### LINKED ISSUE #34: Update repo to JDK17 and AGP 8
With the new Recat Native `0.73.3` version, Android 14 support was added as well as adding support for AGP 8 and Java 17.

We recently [merged a PR](https://github.com/wordpress-mobile/react-native-libraries-publisher/pull/33) with some dependencies updates and the Buildkite job [didn't succeed](https://buildkite.com/automattic/react-native-libraries-publisher/builds/47#018d65c9-90eb-46b2-8e34-7b5ac0ac0b34/164-312) in publishing the binaries:

```
[2024-02-01T17:54:22Z]   bad class file: /root/.gradle/caches/transforms-3/787b90ee41cf1f9225669b74d63cbd4c/transformed/react-android-0.73.3-release-api.jar(/com/facebook/react/bridge/ReactApplicationContext.class)
--
  | [2024-02-01T17:54:22Z]     class file has wrong version 61.0, should be 55.0
  | [2024-02-01T17:54:22Z]     Please remove or make sure it appears in the correct subdirectory of the classpath.
  | [2024-02-01T17:54:22Z] /workdir/node_modules/react-native-get-random-values/android/src/main/java/org/linusu/RNGetRandomValuesModule.java:9: error: cannot access ReactContextBaseJavaModule
  | [2024-02-01T17:54:22Z] import com.facebook.react.bridge.ReactContextBaseJavaModule;

```

It looks like it's related to not building with a newer version of Java.

This problem currently blocks the React Native upgrade.

### PR DESCRIPTION
**Pull request by wzieba**
Closes #34 

## Description

This PR:
- introduces JDK 17 for CI builds
- adds a verification task, `publishToMavenLocal`, to have some way to verify if PR will build when merged to `trunk`

There are two ways to introduce JDK 17:

1. Migrate to `ci_toolkit`. See: https://github.com/wordpress-mobile/react-native-libraries-publisher/pull/37

We could (and maybe should) migrate to `ci_toolkit` and use `nvm_plugin`. I've tried to do this, and I think it worked pretty well, but I stopped on failing build due to lack of `ndk` in the specific version. I've paused my work on this to sync with the rest of Apps Infrastructure what will be the best way to proceed. 

Then, to unblock the team as soon as possible, I pivoted to update the Docker image used in this built. Unfortunately, it turned out to be much more time-consuming than I initially assumed. 

2. Update Docker image

On top of previously used image introduced in https://github.com/wordpress-mobile/docker-android-build-image/pull/7, I've prepared a new image in https://github.com/wordpress-mobile/docker-android-build-image/pull/9 . Please review it before this PR.

### CODE REVIEW

File: .buildkite/pipeline.yml [hunk 1]
```diff
@@ -10,12 +10,17 @@ common-params:
...
+  - label: "Publish to Maven Local (to verify build)"
+    command: |
+      npm install
+      ./gradlew publishToMavenLocal
+    plugins:
+      - *docker-container
   - label: "Publish to S3"
     plugins:
       - *docker-container
+    if: build.branch == "trunk"
```
Comment (wzieba) [inline .buildkite/pipeline.yml:22]: I moved this `if` from `buildkite` configuration to be able to execute PR check:
Screenshot 2024-02-02 at 12 51 29

**Comment by wzieba** [comment]
hi @AliSoftware 👋 Can I get your review on this PR? Context is available in the PR description and in pdnsEh-1vp-p2#comment-3099

I would treat this PR as an intermediate solution to unblock the team ASAP and then work on the `ci_toolkit` migration at #37 .

**Review by AliSoftware — APPROVED** [review]
The `publishToMavenLocal` seems to be [green on CI](https://buildkite.com/automattic/react-native-libraries-publisher/builds/76#018d6b4f-685c-4069-851f-a3fa53d829b9/166-881), so this seems to work as expected.

I agree that, since (at least AFAIU) we mostly dropped our usage of the `Dockerfile` in Buildkite, that change is indeed probably just a temporary fix to unblock things ASAP until you implement the solution in `ci_toolkit`. So approving to unblock.
